name: Bug Report
description: Report an issue that you think is a bug in Flutzig.
body:
  - type: input
    attributes:
      label: Flutzig version
      placeholder: E.g. v1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Laravel version
      placeholder: E.g. v8.38.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Clearly describe the current behaviour you’re seeing, any important steps to reproduce it, and what behaviour you expect instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Flutzig call and context
      render: dart
      description: Where and how you’re using Flutzig when the issue appears.
      placeholder: |
        // E.g.:
        // ApiClient is a wrapper around axios
        ApiClient.get(route(name: 'home', params: { lang: 'en' }));
    validations:
      required: true
  - type: textarea
    attributes:
      label: Flutzig configuration
      render: json
      description: '`log.debug(Flutzig)` and paste the relevant parts here.'
      placeholder: |
        // E.g.:
        {
          url: 'https://big-route-model-binding.com',
          routes: {
            dashboard: {
              uri: 'dashboard',
              methods: ['GET', 'HEAD'],
            },
            // etc...
          },
        }
    validations:
      required: true
  - type: textarea
    attributes:
      label: Route definition
      render: php
      description: Laravel route definitions of the routes related to the issue.
      placeholder: |
        // E.g.:
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    validations:
      required: true
