name: Test
on:
  pull_request:
    paths-ignore: ['*.md']
  push:
    branches: [main, ci, 1.x]
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test:
    name: ${{ matrix.os[0] }}, PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}
    runs-on: ${{ matrix.os[1] }}
    continue-on-error: ${{ matrix.php == 8.3 }}
    strategy:
      matrix:
        os: [[Ubuntu, ubuntu-latest], [Windows, windows-latest]]
        php: [8.1, 8.2, 8.3]
        laravel: [9, 10, 11]
        exclude:
          - php: 8.1
            laravel: 11
        include:
          - php: 8.3
            composer: --ignore-platform-req=php+
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
      - run: composer require laravel/framework:"${{ matrix.laravel }}.*" --no-update --no-interaction
      - uses: ramsey/composer-install@v2
        with:
          composer-options: ${{ matrix.composer }}
      - run: vendor/bin/pest test --testdox --colors=always
